title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field: common.title
      -
        handle: intro
        field: common.intro
      -
        import: prose
      -
        handle: gallery
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 3
          display: 'Gallery Images'
          type: assets
          icon: assets
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: price
        field:
          read_only: false
          type: money
          listable: hidden
          display: Price
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
