title: 'Product with Variants'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          width: 50
          localizable: true
      -
        handle: cover
        field: common.cover
      -
        handle: clients
        field: common.clients
        config:
          validate:
            - required
      -
        handle: product_variants
        field:
          display: 'Product Variants'
          type: product_variants
          icon: product_variants
          listable: hidden
          localizable: true
      -
        import: prose
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
