title: 'Product with Variants'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field: common.title
        config:
          required: true
      -
        handle: cover
        field: common.cover
        config:
          width: 25
      -
        handle: max_quantity
        field:
          default: '1'
          display: 'Max quantity'
          type: integer
          icon: integer
          localizable: true
          listable: hidden
          width: 25
          validate:
            - 'gt:0'
      -
        handle: clients
        field: common.clients
        config:
          display: 'Available to'
          width: 33
          validate:
            - required
      -
        handle: price_visitors
        field:
          read_only: false
          display: 'Visitors price'
          type: money
          icon: generic
          instructions: 'For advertisement purpose'
          localizable: true
          width: 33
          listable: hidden
          if:
            clients: 'equals members'
      -
        handle: price_members
        field:
          read_only: false
          display: 'Members price'
          type: money
          icon: generic
          instructions: 'For advertisement purpose'
          localizable: true
          width: 33
          listable: hidden
          if:
            clients: 'equals visitors'
      -
        handle: metadatas
        field:
          fields:
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
                width: 33
            -
              handle: hint
              field:
                input_type: text
                antlers: false
                display: Hint
                type: text
                icon: text
                width: 33
                listable: hidden
            -
              handle: required
              field:
                default: false
                display: Required
                type: toggle
                icon: toggle
                width: 33
                listable: hidden
          mode: table
          reorderable: true
          display: 'Extra fields'
          type: grid
          icon: grid
          listable: hidden
          localizable: true
      -
        handle: membership
        field:
          default: false
          display: Membership
          type: toggle
          icon: toggle
          localizable: true
          width: 25
          listable: hidden
      -
        handle: membership_until
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Extend until'
          type: date
          icon: date
          localizable: true
          width: 25
          listable: hidden
          if:
            membership: 'equals true'
      -
        handle: insurance
        field:
          default: false
          display: Insurance
          type: toggle
          icon: toggle
          localizable: true
          width: 25
          listable: hidden
      -
        handle: insurance_until
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Extend until'
          type: date
          icon: date
          localizable: true
          width: 25
          listable: hidden
          if:
            insurance: 'equals true'
      -
        handle: product_variants
        field:
          display: 'Product Variants'
          type: product_variants
          icon: product_variants
          listable: hidden
      -
        handle: intro
        field: common.intro
      -
        import: prose
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
