title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field: common.title
        config:
          required: true
      -
        handle: cover
        field: common.cover
        config:
          width: 25
      -
        handle: intro
        field: common.intro
      -
        import: prose
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
  sale:
    display: Sale
    fields:
      -
        handle: max_quantity
        field:
          default: '5'
          display: 'Max quantity'
          type: integer
          icon: integer
          localizable: true
          listable: hidden
          validate:
            - 'gt:0'
          instructions: 'Maximum quantity of that product that can be added to the basket at once. Should be 1 for insurance (the amount depends on the children variant)'
          width: 50
      -
        handle: stock
        field:
          display: Stock
          type: integer
          icon: integer
          localizable: true
          width: 50
          listable: hidden
          instructions_position: above
      -
        handle: availability_and_prices
        field:
          display: 'Availability and prices'
          type: section
          icon: section
          listable: hidden
      -
        handle: clients
        field: common.clients
        config:
          options:
            all: All
            visitors: Non-members
            members: Members
          display: 'Available to'
          width: 33
          validate:
            - required
          instructions: 'Who will see this product in the shop'
      -
        handle: price
        field:
          type: money
          display: Price
          read_only: false
          listable: hidden
          localizable: true
          width: 33
          instructions: 'Actual price when added to basket'
      -
        handle: price_visitors
        field:
          read_only: false
          display: 'Visitors price'
          type: money
          icon: generic
          instructions: 'For advertisement purpose'
          localizable: true
          width: 33
          listable: hidden
          if:
            clients: 'equals members'
      -
        handle: price_members
        field:
          read_only: false
          display: 'Members price'
          type: money
          icon: generic
          instructions: 'For advertisement purpose'
          localizable: true
          width: 33
          listable: hidden
          if:
            clients: 'equals visitors'
      -
        handle: extra_fields
        field:
          display: 'Extra fields'
          type: section
          icon: section
          listable: hidden
      -
        handle: metadatas
        field:
          fields:
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
                width: 33
            -
              handle: hint
              field:
                input_type: text
                antlers: false
                display: Hint
                type: text
                icon: text
                width: 33
                listable: hidden
            -
              handle: required
              field:
                default: false
                display: Required
                type: toggle
                icon: toggle
                width: 33
                listable: hidden
          mode: table
          reorderable: true
          display: 'Extra fields'
          type: grid
          icon: grid
          listable: hidden
          localizable: true
          instructions: 'Extra info you need from the user for that sale'
      -
        handle: membership_and_insurance
        field:
          display: 'Membership & insurance'
          type: section
          icon: section
          instructions: 'Specific fields if the product is a membership and/or an insurance'
          listable: hidden
      -
        handle: membership
        field:
          default: false
          display: Membership
          type: toggle
          icon: toggle
          localizable: true
          width: 25
          listable: hidden
      -
        handle: membership_until
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Extend until'
          type: date
          icon: date
          localizable: true
          width: 25
          listable: hidden
          instructions: 'If this product is bought, will extend the customer membership until'
          if:
            membership: 'equals true'
      -
        handle: insurance
        field:
          default: false
          display: Insurance
          type: toggle
          icon: toggle
          localizable: true
          width: 25
          listable: hidden
      -
        handle: insurance_until
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Extend until'
          type: date
          icon: date
          localizable: true
          width: 25
          listable: hidden
          if:
            insurance: 'equals true'
          instructions: 'If this product is bought, will extend the customer insurance until'
      -
        handle: confirmation_email
        field:
          display: 'Confirmation email'
          type: section
          icon: section
          localizable: true
          listable: hidden
          instructions_position: above
      -
        handle: instructions
        field:
          antlers: false
          display: Instructions
          type: textarea
          icon: textarea
          instructions: 'Will appear in confirmation email if this product is bought'
          localizable: true
          listable: hidden
          instructions_position: above
