title: Products
sites:
  - english
  - french
template: templates/product
layout: layout
mount: 75c0feb7-405d-4d99-8cb4-9932e755f34d
revisions: false
route: '{mount}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
